name: next_js_boiler_plate

services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: next_js_boiler_plate_dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      BUN_HOT: 1
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - next_cache:/app/.next
      - .env.development:/app/.env
    profiles:
      - dev
    develop:
      watch:
        - path: ./next.config.ts
          action: rebuild
        - path: ./tailwind.config.ts
          action: rebuild
        - path: ./Dockerfile.dev
          action: rebuild
        - path: ./package.json
          target: /app/package.json
          action: sync
        - path: ./bun.lock
          target: /app/bun.lock
          action: sync
        - path: .
          target: /app
          action: sync
          ignore:
            - node_modules/
            - .git/
            - .next/
            - dist/
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: next_js_boiler_plate_prod
    restart: unless-stopped
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    volumes:
      - .env.production:/app/.env
    profiles:
      - prod

volumes:
  node_modules:
  next_cache:
