services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sufis_market
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    environment:
      NODE_ENV: production
      NODE_OPTIONS: "--max-old-space-size=4096"
    ports:
      - "3000:3000"
    env_file:
      - .env