import { TProductCard } from "@/types/product.type";

export const productData: TProductCard[] = [
  {
    id: "1",
    title: "Fresh Atlantic Salmon",
    description: "Wild-caught sustainable salmon fillet",
    image: "/images/salmon.png",
    tags: ["Halal", "Gluten-Free"],
    badge: "Buy 1 Get 1",
    rating: 4,
    oldPrice: "14.99",
    price: "11.49",
    unit: "kg",
    stockStatus: "out-of-stock",
    isFavorite: true,
  },
  {
    id: "2",
    title: "Organic Cucumbers",
    description:
      "Crisp and refreshing cucumbers sourced from local farms. Perfect for salads, raita, or light snacking.",
    image: "/images/salmon.png",
    tags: ["Halal", "Vegan"],
    rating: 5,
    oldPrice: "14.99",
    price: "11.49",
    unit: "kg",
    stockStatus: "in-stock",
    isFavorite: false,
  },
  {
    id: "3",
    title: "Premium Basmati Rice",
    description:
      "ong-grain aromatic basmati rice, aged for perfect fluffiness.",
    image: "/images/salmon.png",
    tags: ["Sugar-Free", "Halal"],
    badge: "Buy 1 Get 1",
    rating: 3,
    oldPrice: "14.99",
    price: "11.49",
    unit: "kg",
    stockStatus: "in-stock",
    isFavorite: true,
  },
  {
    id: "4",
    title: "Golden Mustard Oil",
    description:
      "Pure cold-pressed mustard oil with a rich aroma. Excellent for cooking traditional dishes and pickles.",
    image: "/images/salmon.png",
    tags: ["Halal", "Gluten-Free"],
    badge: "Buy 1 Get 1",
    rating: 4,
    oldPrice: "14.99",
    price: "11.49",
    unit: "kg",
    stockStatus: "out-of-stock",
    isFavorite: false,
  },
  {
    id: "5",
    title: "Fresh Farm Eggs",
    description:
      "Farm-fresh brown eggs, high in protein and nutrition. Perfect for breakfast, baking, or hearty meals.",
    image: "/images/salmon.png",
    tags: ["Halal", "Vegan"],
    rating: 5,
    oldPrice: "14.99",
    price: "11.49",
    unit: "kg",
    stockStatus: "out-of-stock",
    isFavorite: true,
  },
  {
    id: "6",
    title: "Organic Red Lentils (Masoor Dal)",
    description:
      "Protein-rich split red lentils. Easy to cook, light on digestion, and perfect for everyday dal curry.",
    image: "/images/salmon.png",
    tags: ["Sugar-Free", "Halal"],
    badge: "Buy 1 Get 1",
    rating: 3,
    oldPrice: "14.99",
    price: "11.49",
    unit: "kg",
    stockStatus: "in-stock",
    isFavorite: false,
  },
  {
    id: "7",
    title: "Brown Sugar",
    description:
      "Natural brown sugar with rich caramel flavor. Great for tea, coffee, and desserts.",
    image: "/images/salmon.png",
    tags: ["Halal", "Gluten-Free"],
    badge: "Buy 1 Get 1",
    rating: 4,
    oldPrice: "14.99",
    price: "11.49",
    unit: "kg",
    stockStatus: "out-of-stock",
    isFavorite: true,
  },
  {
    id: "8",
    title: "Premium Black Tea Leaves",
    description:
      "Strong and flavorful tea leaves handpicked from the finest gardens. Enjoy a refreshing cup any time of day.",
    image: "/images/salmon.png",
    tags: ["Halal", "Vegan"],
    rating: 5,
    oldPrice: "14.99",
    price: "11.49",
    unit: "kg",
    stockStatus: "out-of-stock",
    isFavorite: false,
  },
  {
    id: "9",
    title: "Fresh Green Chili",
    description:
      "Spicy, farm-fresh green chilies to add a kick to your curries and chutneys.",
    image: "/images/salmon.png",
    tags: ["Sugar-Free", "Halal"],
    badge: "Buy 1 Get 1",
    rating: 3,
    oldPrice: "14.99",
    price: "11.49",
    unit: "kg",
    stockStatus: "in-stock",
    isFavorite: true,
  },
];
